export const ADD_COUNT = "ADD_COUNT";
export const ADD_PORT = "ADD_PORT";
export const REMOVE_PORT = "REMOVE_PORT";

export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";

export const FETCH_PRODUCER_SUCCESS = "FETCH_PRODUCER_SUCCESS";
export const FETCH_CONSUMER_SUCCESS = "FETCH_CONSUMER_SUCCESS";
export const FETCH_NETWORK_SUCESS = "FETCH_NETWORK_SUCCESS";
